userName=Super User
password=Wings@123
multiUserApp="C:\\Program Files (x86)\\Wings Infonet Ltd\\Wings 23D Launcher\\WLauncher23D.exe"
singleUserApp="C:\\Program Files (x86)\\Wings Infonet\\Wings Books 24D\\Wings.exe"
serverPath=http://10.10.10.90:5024
platformName=Windows
deviceName=WindowsPC
failedTcReport=false
userLevel=AT_User 1

mobileDevice=Pixel 7
serverURL=https://10.10.10.90:8083
dbName=24D BOOKS AUTOMATION
mobileUserName=Super User

