password=Wings@123
multiUserApp="C:\\Program Files (x86)\\Wings Infonet Ltd\\Wings 23D Launcher\\WLauncher23D.exe"
singleUserApp="C:\\Program Files (x86)\\Wings Infonet\\Wings Books 24D\\Wings.exe"
platformName=Windows
deviceName=WindowsPC
failedTcReport=false
userLevel=AT_User 1
