package com.wings.pages.purchase.masters;

import com.wings.pages.Masters;
import com.wings.utils.Common;
import io.appium.java_client.windows.WindowsDriver;
import org.json.simple.parser.ParseException;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;

import java.awt.*;
import java.awt.event.KeyEvent;
import java.io.IOException;

public class Supplier extends Masters {
 WindowsDriver driver;
 Common common;
 String dataFile;

 public Supplier(WindowsDriver driver, String file) {
  super(driver);
  this.driver = driver;
  common = new Common(this.driver);
  dataFile = file;
 }

 public void createSupplier() throws InterruptedException, IOException, ParseException, AWTException {
  navigateToMastersWhen2Steps("Purchase","Suppliers");
  Thread.sleep(1500);
  createMaster("xpath", "//TreeItem[@Name='Suppliers']/TreeItem[@Name='All Suppliers']");
  Thread.sleep(2500);
  inputTextWithValidation("xpath", "//Edit[@Name='New Supplier *']", common.getData(dataFile, "newSupplier") + common.getRandom());
  String master=common.findWebElement("xpath","//Edit[@Name='New Supplier *']").getText();
  inputTextWithValidation("xpath", "//Edit[@Name='Supplier Code']", common.getData(dataFile, "supplierCode") + common.getRandom());
  inputTextWithValidation("xpath", "//Edit[@Name='Description']", common.getData(dataFile, "desription"));
  common.clickElement("xpath", "//Pane[@Name='Bank Details']/Button[@Name='...']");
  inputTextWithValidation("xpath", "//Edit[@Name='Account No']", common.getData(dataFile, "ACNO"));
  inputTextWithValidation("xpath", "//Edit[@Name='Bank']", common.getData(dataFile, "bank"));
  inputTextWithValidation("xpath", "//Edit[@Name='Bank Branch']", common.getData(dataFile, "bankBranch"));
  inputTextWithValidation("xpath", "//Edit[@Name='IFSC Code']", common.getData(dataFile, "IfscCode"));
  common.clickElement("xpath", "//Button[@Name='Ok']");
  common.clickElement("xpath", "//Edit[@Name='Executive']/Button[@Name='Open']");
  Robot robot = new Robot();
  Thread.sleep(2000);
  robot.keyPress(KeyEvent.VK_DOWN);
  robot.keyRelease(KeyEvent.VK_DOWN);
  robot.keyPress(KeyEvent.VK_DOWN);
  robot.keyRelease(KeyEvent.VK_DOWN);
  robot.keyPress(KeyEvent.VK_DOWN);
  robot.keyRelease(KeyEvent.VK_DOWN);
  robot.keyPress(KeyEvent.VK_ENTER);
  robot.keyRelease(KeyEvent.VK_ENTER);
  common.clickElement("xpath", "//Edit[@Name='Route']");
  Thread.sleep(2000);
  common.clickElement("xpath", "//Edit[@Name='Purchase Price List']/Button[@Name='Open']");
  Thread.sleep(2000);
  robot.keyPress(KeyEvent.VK_DOWN);
  robot.keyRelease(KeyEvent.VK_DOWN);
  robot.keyPress(KeyEvent.VK_ENTER);
  robot.keyRelease(KeyEvent.VK_ENTER);
  common.clickElement("xpath", "//Edit[@Name='Sales Price List']/Button[@Name='Open']");
  Thread.sleep(2000);
  robot.keyPress(KeyEvent.VK_DOWN);
  robot.keyRelease(KeyEvent.VK_DOWN);
  robot.keyPress(KeyEvent.VK_ENTER);
  robot.keyRelease(KeyEvent.VK_ENTER);
  common.clickElement("xpath", "//Edit[@Name='Transport']/Button[@Name='Open']");
  Thread.sleep(2000);
  robot.keyPress(KeyEvent.VK_UP);
  robot.keyRelease(KeyEvent.VK_UP);
  robot.keyPress(KeyEvent.VK_UP);
  robot.keyRelease(KeyEvent.VK_UP);
  robot.keyPress(KeyEvent.VK_ENTER);
  robot.keyRelease(KeyEvent.VK_ENTER);
  common.clickElement("xpath", "//Edit[@Name='Type Of Customer']");
  common.sliderHandling("xpath", "//ScrollBar[@Name='Vertical']/Thumb[@Name='Position']", 0, 400);
  Thread.sleep(2000);
  inputTextWithValidation("xpath", "//Edit[@Name='Aadhaar No']", common.getData(dataFile, "Aadhaar"));
  inputTextWithValidation("xpath", "//Pane[@Name='PartyDescription']/Edit[@Name='Description']", common.getData(dataFile, "Description"));
  Thread.sleep(1000);
  common.clickElement("xpath", "//Pane[@Name='Address and Contact Details']/Button[@Name='...']");
  Thread.sleep(1000);
  inputTextWithValidation("xpath", "//Edit[@Name='Address 1']", common.getData(dataFile, "Address1"));
  inputTextWithValidation("xpath", "//Edit[@Name='Address 2']", common.getData(dataFile, "Address2"));
  inputTextWithValidation("xpath", "//Edit[@Name='Address 3']", common.getData(dataFile, "Address3"));
  inputTextWithValidation("xpath", "//Edit[@Name='City']", common.getData(dataFile, "city"));
  inputTextWithValidation("xpath", "//Edit[@Name='State']", common.getData(dataFile, "state"));
  Thread.sleep(1000);
  WebElement country = common.findWebElement("xpath", "//Edit[@Name='Country']");
  country.clear();
  country.sendKeys(common.getData(dataFile, "country"), Keys.ENTER);
  inputTextWithValidation("xpath", "//Edit[@Name='Zip']", common.getData(dataFile, "zip"));
  inputTextWithValidation("xpath", "//Edit[@Name='Telephones 1']", common.getData(dataFile, "Telephone1"));
  inputTextWithValidation("xpath", "//Edit[@Name='Telephones 2']", common.getData(dataFile, "Telephone2"));
  inputTextWithValidation("xpath", "//Edit[@Name='Telephones 3']", common.getData(dataFile, "Telephone3"));
  inputTextWithValidation("xpath", "//Edit[@Name='Telephones 4']", common.getData(dataFile, "Telephone4"));
  inputTextWithValidation("xpath", "//Edit[@Name='Fax']", common.getData(dataFile, "fax"));
  inputTextWithValidation("xpath", "//Edit[@Name='Email']", common.getData(dataFile, "email"));
  inputTextWithValidation("xpath", "//Edit[@Name='Website']", common.getData(dataFile, "website"));
  inputTextWithValidation("xpath", "//Edit[@Name='Contact Person']", common.getData(dataFile, "contactPersion"));
  inputTextWithValidation("xpath", "//Edit[@Name='Contact Person Designation']", common.getData(dataFile, "contactPersonDesignation"));
  inputTextWithValidation("xpath", "//Edit[@Name='Contact Person Telephone No']", common.getData(dataFile, "contactPersonTelephoneNo"));
  inputTextWithValidation("xpath", "//Edit[@Name='Contact Person Mobile No']", common.getData(dataFile, "contactPersonMobileNo"));
  inputTextWithValidation("xpath", "//Edit[@Name='Contact Person Email']", common.getData(dataFile, "contactPersonEmail"));
  common.clickElement("xpath", "//Button[@Name='Ok']");
  common.sliderHandling("xpath","//*/Thumb[@Name='Position']",0,190);
  common.clickElement("xpath", "//Pane[@Name='Registration']/Button[@Name='...']");
  common.clickElement("xpath", "//Edit[@Name='Party Reg Type *']/Button[@Name='Open']");
  Thread.sleep(2000);
  robot.keyPress(KeyEvent.VK_DOWN);
  robot.keyRelease(KeyEvent.VK_DOWN);
  robot.keyPress(KeyEvent.VK_ENTER);
  robot.keyRelease(KeyEvent.VK_ENTER);
  Thread.sleep(200);
  common.clickElement("xpath", "//Edit[@Name='GSTIN']");
  inputTextWithValidation("xpath", "//Edit[@Name='GSTIN']", common.getData(dataFile, "GstiNO"));
  common.clickElement("xpath", "//Edit[@Name='PAN']");
  Thread.sleep(2000);
  common.clickElement("xpath", "//Button[@Name='Verify GSTIN']");
  Thread.sleep(2000);
  common.clickElement("xpath", "//Window[@Name='Verified result based on GSTIN / UIN']/TitleBar/Button[@Name='Close']");
  common.clickElement("xpath", "//Button[@Name='Ok']");
  common.clickElement("xpath", "//Pane[@Name='Contact Details']/Button[@Name='...']");
  Thread.sleep(2000);
  inputTextWithValidation("xpath", "//Edit[@Name='Telephones 1']", common.getData(dataFile, "Telephone 1"));
  inputTextWithValidation("xpath", "//Edit[@Name='Telephones 2']", common.getData(dataFile, "Telephone 2"));
  inputTextWithValidation("xpath", "//Edit[@Name='Telephones 3']", common.getData(dataFile, "Telephone 3"));
  inputTextWithValidation("xpath", "//Edit[@Name='Telephones 4']", common.getData(dataFile, "Telephone 4"));
  inputTextWithValidation("xpath", "//Edit[@Name='Fax']", common.getData(dataFile, "fax"));
  inputTextWithValidation("xpath", "//Edit[@Name='Email']", common.getData(dataFile, "email"));
  inputTextWithValidation("xpath", "//Edit[@Name='Website']", common.getData(dataFile, "website"));
  inputTextWithValidation("xpath", "//Edit[@Name='Contact Person']", common.getData(dataFile, "contactPersion"));
  inputTextWithValidation("xpath", "//Edit[@Name='Contact Person Designation']", common.getData(dataFile, "contactPersonDesignation"));
  inputTextWithValidation("xpath", "//Edit[@Name='Contact Person Telephone No']", common.getData(dataFile, "contactPersonTelephoneNo"));
  inputTextWithValidation("xpath", "//Edit[@Name='Contact Person Mobile No']", common.getData(dataFile, "contactPersonMobileNo"));
  inputTextWithValidation("xpath", "//Edit[@Name='Contact Person Email']", common.getData(dataFile, "contactPersonemail"));
  Thread.sleep(2000);
  common.clickElement("xpath", "//Button[@Name='Ok']");
  Thread.sleep(2000);
  common.clickElement("xpath", "//CheckBox[@Name='Apply TDS']");
  common.clickElement("xpath", "//Edit[@Name='TDS Assessee Type']/Button[@Name='Open']");
  robot.keyPress(KeyEvent.VK_DOWN);
  robot.keyRelease(KeyEvent.VK_DOWN);
  robot.keyPress(KeyEvent.VK_ENTER);
  robot.keyRelease(KeyEvent.VK_ENTER);
  common.clickElement("xpath", "//CheckBox[@Name='Apply TCS']");
  common.clickElement("xpath", "//Edit[@Name='TCS Assessee Type']/Button[@Name='Open']");
//  inputTextWithValidation("xpath", "//Edit[@Name='Date Of Birth']", common.getData(dataFile, "dateOfBirth"));
//  inputTextWithValidation("xpath", "//Edit[@Name='Anniversary Date']", common.getData(dataFile, "anniversaryDate"));
  Thread.sleep(1500);
  common.clickElement("xpath", "//Text[@Name='Shipping Address GST']/following-sibling::Button[@Name='...']");
  Thread.sleep(2000);
  common.clickElement("xpath", "//Edit[@Name='GSTIN Row 0, Not sorted.']");
  common.inputText("xpath", "//Edit[@Name='GSTIN Row 0, Not sorted.']", common.getData(dataFile, "GstiNO"));
  common.clickElement("xpath", "//Edit[@Name='Address Name * Row 0, Not sorted.']");
  common.inputText("xpath", "//Edit[@Name='Address Name * Row 0, Not sorted.']", common.getData(dataFile, "shippingAdressName"));
  common.clickElement("xpath", "//Edit[@Name='Address 1 * Row 0, Not sorted.']");
  common.inputText("xpath", "//Edit[@Name='Address 1 * Row 0, Not sorted.']", common.getData(dataFile, "ShippingAdress1"));
  common.inputText("xpath", "//Edit[@Name='Address 2 Row 0, Not sorted.']", common.getData(dataFile, "ShippingAdress2"));
  common.inputText("xpath", "//Edit[@Name='Address 3 Row 0, Not sorted.']", common.getData(dataFile, "ShippingAdress3"));
  common.clickElement("xpath", "//Edit[@Name='City * Row 0, Not sorted.']");
  common.inputText("xpath", "//Edit[@Name='City * Row 0, Not sorted.']", common.getData(dataFile, "Shippingcity"));
  WebElement state = common.findWebElement("xpath", "//Edit[@Name='State * Row 0, Not sorted.']");
  state.click();
  state.sendKeys(common.getData(dataFile, "ShippingState"), Keys.ENTER);
  Thread.sleep(3000);

  int offset = 300;
  WebElement slider1 = common.findWebElement("xpath", "//ScrollBar[@Name='Horizontal']/Thumb[@Name='Position']");
  Actions actions = new Actions(driver);
  actions.clickAndHold(slider1).moveByOffset(offset, 0).release().perform();

  common.clickElement("xpath", "//Edit[@Name='Zip/PostalCode * Row 0, Not sorted.']");
  common.inputText("xpath", "//Edit[@Name='Zip/PostalCode * Row 0, Not sorted.']", common.getData(dataFile, "stateZipcode"));
  common.clickElement("xpath", "//Edit[@Name='Country * Row 0, Not sorted.']");
  WebElement country1 = common.findWebElement("xpath", "//Edit[@Name='Country * Row 0, Not sorted.']");
  country1.click();
  country1.sendKeys(common.getData(dataFile, "country"), Keys.ENTER);
  Thread.sleep(2000);
  common.clickElement("xpath", "//Button[@Name='Ok']");
  Thread.sleep(2000);
  common.clickElement("xpath", "//Text[@Name='Account Group']/following-sibling::Button[@Name='...']");
  WebElement accountGroup = common.findWebElement("xpath", "//Edit[@Name='Account Group Row 0, Not sorted.']");
  accountGroup.click();
  accountGroup.sendKeys(common.getData(dataFile, "accountGroup"), Keys.ENTER);
  common.clickElement("xpath", "//Button[@Name='Ok']");

//  common.clickElement("xpath", "//Text[@Name='Consignor']/following-sibling::Button[@Name='...']");
//  WebElement consigner = common.findWebElement("xpath", "//Edit[@Name='Applicable Consignor Row 0, Not sorted.']");
//  consigner.click();
//  consigner.sendKeys(common.getData(dataFile, "consigner"), Keys.ENTER);
//  common.clickElement("xpath", "//Button[@Name='Ok']");
  saveAfterMasterCreate();
  validateMastersAndInactive("Suppliers",master);
 }
}
